---
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: observability-obc
  namespace: open-cluster-management-observability
  annotations:
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
    argocd.argoproj.io/sync-wave: "7"    
spec:
  generateBucketName: observability-object-bucket
  storageClassName: openshift-storage.noobaa.io
