allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    description: Provides RWO Filesystem volumes, and RWO and RWX Block volumes
    reclaimspace.csiaddons.openshift.io/schedule: '@weekly'
    storageclass.kubernetes.io/is-default-class: "true"
    argocd.argoproj.io/sync-options: ServerSideApply=true,Validate=false
    argocd.argoproj.io/sync-wave: "4"
  name: ocs-storagecluster-ceph-rbd
