apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  annotations:
    capability.openshift.io/name: Console
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
spec:
  customization:
    addPage: {}
    capabilities:
    - name: LightspeedButton
      visibility:
        state: Enabled
    customLogoFile:
      name: ""
    developerCatalog:
      types:
        state: Enabled
    projectAccess: {}
    quickStarts: {}
  ingress:
    clientDownloadsURL: ""
    consoleURL: ""
  logLevel: Normal
  managementState: Managed
  observedConfig: null
  operatorLogLevel: Normal
  plugins:
  - gitops-plugin
  - monitoring-plugin
  - networking-console-plugin
  providers: {}
  route:
    hostname: ""
    secret:
      name: ""
  unsupportedConfigOverrides: null
    status: "False"
