apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  annotations:
    capability.openshift.io/name: Console
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    release.openshift.io/create-only: "true"
  creationTimestamp: "2025-01-21T17:44:23Z"
  generation: 4
  name: cluster
  ownerReferences:
  - apiVersion: config.openshift.io/v1
    kind: ClusterVersion
    name: version
    uid: 44f0200f-1dbd-44b2-a5e9-62ddfa3cdb00
  resourceVersion: "533532"
  uid: f95bc0c2-d183-4fcb-8e21-4510399b31df
spec:
  customization:
    addPage: {}
    capabilities:
    - name: LightspeedButton
      visibility:
        state: Enabled
    customLogoFile:
      name: ""
    developerCatalog:
      types:
        state: Enabled
    projectAccess: {}
    quickStarts: {}
  ingress:
    clientDownloadsURL: ""
    consoleURL: ""
  logLevel: Normal
  managementState: Managed
  observedConfig: null
  operatorLogLevel: Normal
  plugins:
  - gitops-plugin
  - monitoring-plugin
  - networking-console-plugin
  providers: {}
  route:
    hostname: ""
    secret:
      name: ""
  unsupportedConfigOverrides: null
status:
  conditions:
  - lastTransitionTime: "2025-01-21T17:44:37Z"
    status: "False"
    type: ConsoleNotificationSyncDegraded
  - lastTransitionTime: "2025-01-21T17:44:37Z"
    status: "False"
    type: ConsoleNotificationSyncProgressing
  - lastTransitionTime: "2025-01-21T17:45:09Z"
    status: "False"
    type: SyncLoopRefreshDegraded
  - lastTransitionTime: "2025-01-21T18:25:04Z"
    status: "False"
    type: SyncLoopRefreshProgressing
  - lastTransitionTime: "2025-01-21T17:44:37Z"
    status: "False"
    type: DownloadsDeploymentSyncDegraded
  - lastTransitionTime: "2025-01-21T17:44:37Z"
    status: "False"
    type: DownloadsDeploymentSyncProgressing
  - lastTransitionTime: "2025-01-21T17:44:41Z"
    status: "False"
    type: DownloadsCustomRouteSyncDegraded
  - lastTransitionTime: "2025-01-21T17:44:41Z"
    status: "False"
    type: DownloadsCustomRouteSyncProgressing
  - lastTransitionTime: "2025-01-21T17:44:41Z"
    status: "True"
    type: DownloadsCustomRouteSyncUpgradeable
  - lastTransitionTime: "2025-01-21T17:44:44Z"
    status: "False"
    type: DownloadsDefaultRouteSyncDegraded
  - lastTransitionTime: "2025-01-21T17:44:41Z"
    status: "False"
    type: DownloadsDefaultRouteSyncProgressing
  - lastTransitionTime: "2025-01-21T17:44:44Z"
    status: "True"
    type: DownloadsDefaultRouteSyncUpgradeable
  - lastTransitionTime: "2025-01-21T17:44:47Z"
    status: "False"
    type: PDBSyncDegraded
  - lastTransitionTime: "2025-01-21T17:44:47Z"
    status: "False"
    type: PDBSyncProgressing
  - lastTransitionTime: "2025-01-21T17:44:50Z"
    status: "True"
    type: ConsoleDefaultRouteSyncUpgradeable
  - lastTransitionTime: "2025-01-21T17:44:50Z"
    status: "False"
    type: ConsoleCustomRouteSyncDegraded
  - lastTransitionTime: "2025-01-21T17:44:50Z"
    status: "False"
    type: ConsoleCustomRouteSyncProgressing
  - lastTransitionTime: "2025-01-21T17:44:50Z"
    status: "True"
    type: ConsoleCustomRouteSyncUpgradeable
  - lastTransitionTime: "2025-01-21T17:44:50Z"
    status: "False"
    type: ConsoleDefaultRouteSyncDegraded
  - lastTransitionTime: "2025-01-21T17:44:50Z"
    status: "False"
    type: ConsoleDefaultRouteSyncProgressing
  - lastTransitionTime: "2025-01-21T17:44:52Z"
    status: "False"
    type: ServiceSyncProgressing
  - lastTransitionTime: "2025-01-21T17:44:52Z"
    status: "False"
    type: ServiceSyncDegraded
  - lastTransitionTime: "2025-01-21T17:47:13Z"
    status: "False"
    type: RouteHealthDegraded
  - lastTransitionTime: "2025-01-21T17:44:55Z"
    status: "False"
    type: RouteHealthProgressing
  - lastTransitionTime: "2025-01-21T17:47:13Z"
    status: "True"
    type: RouteHealthAvailable
  - lastTransitionTime: "2025-01-21T17:44:57Z"
    status: "False"
    type: OCDownloadsSyncDegraded
  - lastTransitionTime: "2025-01-21T17:44:57Z"
    status: "False"
    type: ODODownloadsSyncDegraded
  - lastTransitionTime: "2025-01-21T17:45:14Z"
    reason: AsExpected
    status: "False"
    type: OAuthClientsControllerDegraded
  - lastTransitionTime: "2025-01-21T17:45:01Z"
    status: "False"
    type: OAuthClientSyncDegraded
  - lastTransitionTime: "2025-01-21T17:45:01Z"
    status: "False"
    type: OAuthClientSyncProgressing
  - lastTransitionTime: "2025-01-21T17:45:03Z"
    status: "False"
    type: AuthStatusHandlerProgressing
  - lastTransitionTime: "2025-01-21T17:45:03Z"
    status: "False"
    type: OIDCClientConfigDegraded
  - lastTransitionTime: "2025-01-21T17:45:03Z"
    status: "False"
    type: OIDCClientConfigProgressing
  - lastTransitionTime: "2025-01-21T17:45:03Z"
    status: "False"
    type: AuthStatusHandlerDegraded
  - lastTransitionTime: "2025-01-21T17:45:05Z"
    status: "False"
    type: OAuthClientSecretSyncDegraded
  - lastTransitionTime: "2025-01-21T17:45:05Z"
    status: "False"
    type: OAuthClientSecretSyncProgressing
  - lastTransitionTime: "2025-01-21T17:45:06Z"
    reason: NoUnsupportedConfigOverrides
    status: "True"
    type: UnsupportedConfigOverridesUpgradeable
  - lastTransitionTime: "2025-01-21T17:45:08Z"
    status: "False"
    type: ResourceSyncControllerDegraded
  - lastTransitionTime: "2025-01-21T17:45:09Z"
    status: "False"
    type: ConfigMapSyncDegraded
  - lastTransitionTime: "2025-01-21T17:45:09Z"
    status: "False"
    type: ConfigMapSyncProgressing
  - lastTransitionTime: "2025-01-21T17:45:09Z"
    status: "False"
    type: CustomLogoSyncDegraded
  - lastTransitionTime: "2025-01-21T17:45:09Z"
    status: "False"
    type: OAuthServingCertValidationProgressing
  - lastTransitionTime: "2025-01-21T17:45:09Z"
    status: "False"
    type: OAuthClientSecretGetProgressing
  - lastTransitionTime: "2025-01-21T17:50:28Z"
    status: "False"
    type: DeploymentSyncDegraded
  - lastTransitionTime: "2025-01-21T17:45:09Z"
    status: "False"
    type: DeploymentSyncProgressing
  - lastTransitionTime: "2025-01-21T17:47:13Z"
    status: "True"
    type: DeploymentAvailable
  - lastTransitionTime: "2025-01-21T17:45:09Z"
    status: "False"
    type: ConsoleConfigDegraded
  - lastTransitionTime: "2025-01-21T17:45:09Z"
    status: "False"
    type: ServiceCASyncDegraded
  - lastTransitionTime: "2025-01-21T17:45:09Z"
    status: "False"
    type: ServiceCASyncProgressing
  - lastTransitionTime: "2025-01-21T17:45:09Z"
    status: "False"
    type: TrustedCASyncDegraded
  - lastTransitionTime: "2025-01-21T17:45:09Z"
    status: "False"
    type: OAuthClientSecretGetDegraded
  - lastTransitionTime: "2025-01-21T17:45:09Z"
    status: "False"
    type: TrustedCASyncProgressing
  - lastTransitionTime: "2025-01-21T17:45:09Z"
    status: "False"
    type: CustomLogoSyncProgressing
  - lastTransitionTime: "2025-01-21T17:45:09Z"
    status: "False"
    type: OAuthServingCertValidationDegraded
  - lastTransitionTime: "2025-01-21T17:45:09Z"
    status: "False"
    type: ConsolePublicConfigMapDegraded
  - lastTransitionTime: "2025-01-21T17:45:12Z"
    status: "False"
    type: ManagementStateDegraded
  - lastTransitionTime: "2025-01-21T17:45:13Z"
    status: "False"
    type: RedirectServiceSyncDegraded
  - lastTransitionTime: "2025-01-21T17:45:13Z"
    status: "False"
    type: RedirectServiceSyncProgressing
  - lastTransitionTime: "2025-01-21T17:45:14Z"
    status: "False"
    type: CLIAuthStatusHandlerProgressing
  - lastTransitionTime: "2025-01-21T17:45:14Z"
    status: "False"
    type: CLIOIDCClientStatusDegraded
  - lastTransitionTime: "2025-01-21T17:45:14Z"
    status: "False"
    type: CLIOIDCClientStatusProgressing
  - lastTransitionTime: "2025-01-21T17:45:14Z"
    status: "False"
    type: CLIAuthStatusHandlerDegraded
  generations:
  - group: apps
    hash: ""
    lastGeneration: 1
    name: downloads
    namespace: openshift-console
    resource: deployments
  - group: apps
    hash: ""
    lastGeneration: 7
    name: console
    namespace: openshift-console
    resource: deployments
  observedGeneration: 4
  readyReplicas: 2
