---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
  - path: patching-console.yaml
    target: 
      kind: consoles.operator.openshift.io
      name: Console 
resources:  
#  - lso/
#  - test/
#  - odf/
