apiVersion: operator.openshift.io/v1
kind: Console
metadata:
  name: cluster
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true,ServerSideApply=true,Validate=false
spec:
  plugins:
  - gitops-plugin
  - monitoring-plugin
  - networking-console-plugin
  - odf-console
