apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test
  namespace: openshift-gitops
spec:
  destination: 
    server: "https://kubernetes.default.svc"
    namespace: default
  project: infra
  syncPolicy:
    automated:
      allowEmpty: true
      selfHeal: true
      prune: true
  syncOptions:
  - CreateNamespace=true
  source:
    path: infra
    repoURL: 'https://github.com/mmorency2021/argocd-operators.git'
    targetRevision: main
