apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-rbac-cm
  namespace: openshift-gitops
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  policy.csv: |
    g, ocp4-cluster-admins, role:admin
  policy.default: ''
  scopes: '[groups]'
