---
apiVersion: v1
kind: Namespace
metadata:
 name: openshift-local-storage
 annotations:
   argocd.argoproj.io/sync-wave: "0"

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
 name: local-operator-group
 namespace: openshift-local-storage
 annotations:
   argocd.argoproj.io/sync-wave: "1"
spec:
 targetNamespaces:
 - openshift-local-storage

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
 name: local-storage-operator
 namespace: openshift-local-storage
 annotations:
   argocd.argoproj.io/sync-wave: "1"
spec:
 channel: "4.17"  # <-- Channel should be used corresponding to the OCP version being used.
 installPlanApproval: Automatic
 name: local-storage-operator
 source: redhat-operators  # <-- Modify the name of the redhat-operators catalogsource if not default
 sourceNamespace: openshift-marketplace

---
apiVersion: local.storage.openshift.io/v1alpha1
kind: LocalVolumeDiscovery
metadata:
 name: auto-discover-devices
 namespace: openshift-local-storage
 annotations:
   argocd.argoproj.io/sync-wave: "2"
spec:
 nodeSelector:
   nodeSelectorTerms:
     - matchExpressions:
       - key: cluster.ocs.openshift.io/openshift-storage
         operator: In
         values:
           - ""
---

---
apiVersion: "local.storage.openshift.io/v1"
kind: "LocalVolume"
metadata:
  name: "local-disks"
  namespace: "openshift-local-storage"
 annotations:
   argocd.argoproj.io/sync-wave: "3"
spec:
  nodeSelector:
    nodeSelectorTerms:
    - matchExpressions:
        - key: cluster.ocs.openshift.io/openshift-storage
          operator: In
          values:
          - ""
  storageClassDevices:
    - storageClassName: "local-sc"
      forceWipeDevicesAndDestroyAllData: true
      volumeMode: Block
      devicePaths:
        - /dev/disk/by-path/pci-0000:18:00.0-scsi-0:2:0:0
